services:
  api:
    build:
      context: .
      dockerfile: src/TaskManagement.Api/Dockerfile
    container_name: task-management.api
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5003
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: task-management.mssql
    ports:
      - "5533:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pass12345$
