name: Build
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: Run Persistence Tests
        run: dotnet test TaskManagement.Persistence.Tests/TaskManagement.Persistence.Tests.csproj --configuration Release --restore
      
      - name: Run Service Tests
        run: dotnet test TaskManagement.Service.Tests/TaskManagement.Service.Tests.csproj --configuration Release --restore
